name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Access api
      run: cd api

    - name: Check for package-lock.json
      run: |
        if [ ! -f "package-lock.json" ]; then
          echo "Error: package-lock.json not found. Run 'npm install' to generate it."
          exit 1
        fi

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Add the following steps for Docker setup
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
    - name: Start MongoDB Docker container
      run: docker run -d --name mongodb -p 27017:27017 mongo

    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    # Navigate back to the root folder
    - name: Change Directory back to the root
      run: cd ..

    # Add the following step to stop and remove the MongoDB Docker container after tests
    - name: Stop and Remove MongoDB Docker container
      run: docker stop mongodb && docker rm mongodb
